name = "flux"
description = "Experimental data stream library for Ada"
version = "0.1.0-dev"
licenses = "Apache-2.0"

authors = ["Fabien Chouteau"]
maintainers = ["Fabien Chouteau <chouteau@adacore.com>"]
maintainers-logins = ["Fabien-Chouteau"]
